"""
ReportLab Layout Templates, Header/Footer Banners, and Color Schemes for TRANSLARA.
"""
from __future__ import annotations

from pathlib import Path
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from backend.ml_engine.languages import get_language
from backend.pedagogy.fonts import get_font_for_language

# Page geometry
PAGE_W, PAGE_H = A4
MARGIN = 15 * mm
PRINTABLE_W = PAGE_W - 2 * MARGIN
PRINTABLE_H = PAGE_H - 2 * MARGIN

# Modern Vibrant Palette
COLOR_TEAL = HexColor("#0f766e")
COLOR_EMERALD = HexColor("#059669")
COLOR_PURPLE = HexColor("#7c3aed")
COLOR_BLUE = HexColor("#2563eb")
COLOR_ORANGE = HexColor("#ea580c")
COLOR_DARK = HexColor("#0f172a")
COLOR_LIGHT_BG = HexColor("#f8fafc")
COLOR_MUTED = HexColor("#64748b")
COLOR_BORDER = HexColor("#cbd5e1")


def draw_pedagogy_header(
    c: canvas.Canvas,
    title: str,
    source_lang: str = "ta",
    target_lang: str = "ml",
    subtitle: str = "Real-Time Vernacular Learning",
) -> float:
    """Draw standardized header on A4 canvas."""
    src_cfg = get_language(source_lang)
    tgt_cfg = get_language(target_lang)
    src_name = src_cfg.name if src_cfg else source_lang.upper()
    tgt_name = tgt_cfg.name if tgt_cfg else target_lang.upper()

    header_y = PAGE_H - MARGIN

    # Top color stripe
    c.setFillColor(COLOR_TEAL)
    c.rect(MARGIN, header_y - 2 * mm, PRINTABLE_W, 2 * mm, fill=1, stroke=0)

    # App Branding
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(COLOR_MUTED)
    c.drawString(MARGIN, header_y - 8 * mm, "TRANSLARA")

    c.setFont("Helvetica", 8)
    c.drawRightString(
        PAGE_W - MARGIN,
        header_y - 8 * mm,
        f"Multilingual Pedagogy ({src_name} ⇄ {tgt_name})",
    )

    # Document Title
    src_font = get_font_for_language(source_lang)
    c.setFont(src_font, 18)
    c.setFillColor(COLOR_DARK)
    c.drawString(MARGIN, header_y - 17 * mm, title)

    # Subtitle
    c.setFont("Helvetica", 9)
    c.setFillColor(COLOR_MUTED)
    c.drawString(MARGIN, header_y - 22 * mm, subtitle)

    # Divider line
    c.setStrokeColor(COLOR_BORDER)
    c.setLineWidth(0.75)
    c.line(MARGIN, header_y - 25 * mm, PAGE_W - MARGIN, header_y - 25 * mm)

    return header_y - 28 * mm


def draw_pedagogy_footer(c: canvas.Canvas, page_num: int = 1, total_pages: int = 1) -> None:
    """Draw standardized footer with page numbers and authenticity badge."""
    c.setStrokeColor(COLOR_BORDER)
    c.setLineWidth(0.5)
    c.line(MARGIN, MARGIN + 8 * mm, PAGE_W - MARGIN, MARGIN + 8 * mm)

    c.setFont("Helvetica", 7.5)
    c.setFillColor(COLOR_MUTED)
    c.drawString(
        MARGIN,
        MARGIN + 3 * mm,
        "Generated by TRANSLARA • AI-Powered Multilingual Pedagogy Engine",
    )

    c.drawRightString(
        PAGE_W - MARGIN,
        MARGIN + 3 * mm,
        f"Page {page_num} of {total_pages}",
    )
